### PR TITLE
Setup dotenv to load env variables

### PR DESCRIPTION
**Pull request by SVijayB**
Switched from local_settings.py to .env using [python-dotenv](https://pypi.org/project/python-dotenv/).

Converted `local_settings_example.py` to `.env.example`.

Should be able to read variables both from the environment and from .env.
.env variables do not overload environment variables.

**Note:**  Haven't tested it out. So you probably might want to do that before merging.

### CODE REVIEW

**Comment by SVijayB** [comment]
Converted from python-dotenv to [dynaconf](https://www.dynaconf.com/).
`settings.toml` - Stores variables.
`.secrets.toml` - Stores secret env variables.

Categorized a few of the variables. 
Keys in `settings.toml` can also be further categorized if and when needed.

**Review by realaravinth — CHANGES_REQUESTED** [review]
Everything appears to be in order but please run `make lint && make freeze` and update your changes

**Comment by SVijayB** [comment]
I had already formatted the code using black. 
Updated requirements as requested.

**Comment by realaravinth** [comment]
weird, runing lint on your copy made some changes to the working tree but that's alright. We'll setup hooks to automate these chores

**Review by dat-adi — COMMENTED** [review]
I suggest that we create a `configs/` or `config/` folder to store our settings, rather than contain all of these configuration files in the `interface/` directory.
That would lead to a cleaner project structure.

Could be implemented by altering the `settings_files` variables present in `config.py`.

For reference,
```py
settings_files=['configs/settings.toml']
```

**Comment by realaravinth** [comment]
closing in favor of #25

**Pull request closed without merging**
